name: site_accordion
displayname: Accordion
table: cms_site_partial_accordion
enabled: true
columns:
  title:
    type: text
    length: 100
    enabled: false
    required : false
meta:
  name: item
  table: cms_site_partial_accordion_items
  order:
    column: displayorder
    order: asc
    manageable: true
    display: title
  columns:
    title:
      label: Title
      type: text
      length: 255
      enabled: true
      required: true
    content:
      type: textarea
      length: 4096
      enabled: true
      required: true
    displayorder:
      type: hidden
      length: 11
      enabled: true
      required: false