name: dropdown
displayname: Form Dropdown Options
table: cms_site_partial_dropdown
enabled: true
columns:
  name:
    type: text
    length: 255
    enabled: true
    required : true
  input_name:
    type: text
    length: 255
    enabled: true
    required : true
meta:
  name: options
  table: cms_site_partial_dropdown_options
  order:
    column: displayorder
    order: asc
    manageable: true
    display: option
  columns:
    option:
      type: text
      length: 255
      enabled: true
      required: true
    displayorder:
      type: hidden
      length: 11
      enabled: true
      required: false